somecoolstuff/apps/coolapi/lib/coolapi_web/router.ex
defmodule CoolapiWeb.Router do
  use CoolapiWeb, :router

  alias CampusLabWeb.Plug.AuthenticateToken

  pipeline :browser do
    plug(:accepts, ["json","html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :protected do
    plug(:accepts, ["json","html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)

    plug(AuthenticateToken)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", CoolapiWeb do
    pipe_through(:protected)



  end

  scope "/", CoolapiWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
    resources("/users", UserController, only: [:new, :create])
    get("/auth/new", SessionController, :new)
    post("/auth", SessionController, :login)
  end

  # Other scopes may use custom stacks.
  # scope "/api", CoolapiWeb do
  #   pipe_through :api
  # end
end

somecoolstuff/apps/coolapi/lib/coolapi/accounts/accounts.ex
defmodule Coolapi.Accounts do
  @moduledoc """
  The Accounts context.
  """

  import Ecto.Query, warn: false
  alias Coolapi.Repo

  alias Coolapi.Accounts.User

  @doc """
  Returns the list of users.

  ## Examples

      iex> list_users()
      [%User{}, ...]

  """
  def list_users do
    Repo.all(User)
  end

  @doc """
  Gets a single user.

  Raises `Ecto.NoResultsError` if the User does not exist.

  ## Examples

      iex> get_user!(123)
      %User{}

      iex> get_user!(456)
      ** (Ecto.NoResultsError)

  """
  def get_user!(id), do: Repo.get!(User, id)

  @doc """
  Creates a user.

  ## Examples

      iex> create_user(%{field: value})
      {:ok, %User{}}

      iex> create_user(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_user(attrs \\ %{}) do
    %User{}
    |> User.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a user.

  ## Examples

      iex> update_user(user, %{field: new_value})
      {:ok, %User{}}

      iex> update_user(user, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_user(%User{} = user, attrs) do
    user
    |> User.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a User.

  ## Examples

      iex> delete_user(user)
      {:ok, %User{}}

      iex> delete_user(user)
      {:error, %Ecto.Changeset{}}

  """
  def delete_user(%User{} = user) do
    Repo.delete(user)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking user changes.

  ## Examples

      iex> change_user(user)
      %Ecto.Changeset{source: %User{}}

  """
  def change_user(%User{} = user) do
    User.changeset(user, %{})
  end

  def get_user_by_email(%User{} = email) do
    Repo.all(from(u in User, where: u.email == ^email))
  end
end

somecoolstuff/apps/coolapi/lib/coolapi/accounts/user.ex
defmodule Coolapi.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset

  @create_fields ~w(name password email)a
  @optional_fields ~w(token)a

  schema "users" do
    field(:email, :string)
    field(:name, :string)
    field(:password, :string)
    field(:token, :string)

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    attrs = Map.put(attrs, "token", Ecto.UUID.generate())
    user
    |> cast(attrs, @create_fields ++ @optional_fields)
    |> validate_required(@create_fields)
  end
end

somecoolstuff/apps/coolapi/lib/coolapi/application.ex
defmodule Coolapi.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Coolapi.Repo,
      # Start the endpoint when the application starts
      CoolapiWeb.Endpoint
      # Starts a worker by calling: Coolapi.Worker.start_link(arg)
      # {Coolapi.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Coolapi.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    CoolapiWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

somecoolstuff/apps/coolapi/lib/coolapi/repo.ex
defmodule Coolapi.Repo do
  use Ecto.Repo,
    otp_app: :coolapi,
    adapter: Ecto.Adapters.Postgres
end

somecoolstuff/apps/coolapi/lib/coolapi_web/controllers/page_controller.ex
defmodule CoolapiWeb.PageController do
  use CoolapiWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

somecoolstuff/apps/coolapi/lib/coolapi_web/controllers/session_controller.ex
defmodule CoolapiWeb.SessionController do
  use CoolapiWeb, :controller
  use OAuth2.Strategy

  # alias Coolapi.Auth
  # alias Coolapi.Auth.Session
  alias Coolapi.Accounts
  alias Coolapi.Accounts.User

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def login(conn, params) do
    IO.inspect(params)

    case Accounts.get_user_by_email(params["email"]) do
      require IEx
      IEx.pry()
      {:ok, user} ->
        IO.inspect(user)

      {:error, info} ->
        IO.inspect(info)
    end

    render(conn, "new.html")
  end

  defp create_client() do
    OAuth2.Client.new(
      strategy: __MODULE__,
      client_id: 1
    )
  end
end

somecoolstuff/apps/coolapi/lib/coolapi_web/controllers/user_controller.ex
defmodule CoolapiWeb.UserController do
  use CoolapiWeb, :controller

  alias Coolapi.Accounts
  alias Coolapi.Accounts.User

  def index(conn, _params) do
    users = Accounts.list_users()
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do


    case Accounts.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    changeset = Accounts.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Accounts.get_user!(id)

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    {:ok, _user} = Accounts.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: Routes.user_path(conn, :index))
  end
end

somecoolstuff/apps/coolapi/lib/coolapi_web/views/error_view.ex
defmodule CoolapiWeb.ErrorView do
  use CoolapiWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

somecoolstuff/apps/coolapi/lib/coolapi_web/views/layout_view.ex
defmodule CoolapiWeb.LayoutView do
  use CoolapiWeb, :view
end

somecoolstuff/apps/coolapi/lib/coolapi_web/views/page_view.ex
defmodule CoolapiWeb.PageView do
  use CoolapiWeb, :view
end

somecoolstuff/apps/coolapi/lib/coolapi_web/views/session/session_view.ex
defmodule CoolapiWeb.SessionView do
  use CoolapiWeb, :view
end

somecoolstuff/apps/coolapi/lib/coolapi_web/views/user/user_view.ex
defmodule CoolapiWeb.UserView do
  use CoolapiWeb, :view
end

somecoolstuff/apps/coolapi/lib/coolapi_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Coolapi</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
        <h1> Cool Blog <h1>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

somecoolstuff/apps/coolapi/lib/coolapi_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "The Coolest Thing Ever" %></h1>
  <p>A cool and random thing that no one uses!</p>
</section>

<section class="row">
  <article class="column">
    <h3>
      Login <%= link "+", to: Routes.session_path(@conn, :new), class: "btn btn-success" %>
    </h3>
  </article>

  <article class="column">
    <h3>
      Create Account <%= link "+", to: Routes.user_path(@conn, :new), class: "btn btn-success" %>
    </h3>
  </article>
</section>

somecoolstuff/apps/coolapi/lib/coolapi_web/templates/session/form.html.eex
<%= form_for @conn, @action, fn f -> %>

  <%= label f, :email %>
  <%= text_input f, :email %>
  <%= error_tag f, :email %>

  <%= label f, :password %>
  <%= text_input f, :password %>
  <%= error_tag f, :password %>

  <div>
    <%= submit "Entrar" %>
  </div>
<% end %>

somecoolstuff/apps/coolapi/lib/coolapi_web/templates/session/new.html.eex
<h1>Login</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.session_path(@conn, :login)) %>

<span><%= link "Back", to: Routes.page_path(@conn, :index) %></span>

somecoolstuff/apps/coolapi/lib/coolapi_web/templates/user/edit.html.eex
<h1>Edit User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

somecoolstuff/apps/coolapi/lib/coolapi_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :email %>
  <%= text_input f, :email %>
  <%= error_tag f, :email %>

  <%= label f, :password %>
  <%= text_input f, :password %>
  <%= error_tag f, :password %>
  
  <div>
    <%= submit "Save" %>
  </div>
<% end %>

somecoolstuff/apps/coolapi/lib/coolapi_web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Token</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.password %></td>
      <td><%= user.token %></td>

      <td>
        <%= link "Show", to: Routes.user_path(@conn, :show, user) %>
        <%= link "Edit", to: Routes.user_path(@conn, :edit, user) %>
        <%= link "Delete", to: Routes.user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: Routes.user_path(@conn, :new) %></span>

somecoolstuff/apps/coolapi/lib/coolapi_web/templates/user/new.html.eex
<h1>New User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.page_path(@conn, :index) %></span>

somecoolstuff/apps/coolapi/lib/coolapi_web/templates/user/show.html.eex
<h1>Show User</h1>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @user.name %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>

  <li>
    <strong>Password:</strong>
    <%= @user.password %>
  </li>

  <li>
    <strong>Token:</strong>
    <%= @user.token %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.user_path(@conn, :edit, @user) %></span>
<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>